name: Build Python Package (dummy)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  repository_dispatch:
    types: [build-package]

jobs:
  package-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.client_payload.ref != '' && github.event.client_payload.ref || github.ref }}"
